server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HarshavardhanaJT/personal-config-store.git
          search-paths:
          - 'service-config\*service'
